### ISSUE TITLE
support any hyperlog-like structure?

### ISSUE THREAD

**Issue by elsehow** [elsehow/identity-swarm#4]
we may want to use a swarmlog, but we may also want to use an [ipfs-hyperlog](https://github.com/noffle/ipfs-hyperlog), or a regular [hyperlog](https://github.com/mafintosh/hyperlog)

i propose that a hyperlog-like object is passed into the constructor

**Comment by harperj** [comment]
Fixed as part of a54ed64.

We might be able to do even better by only requiring a merkle tree data structure, but doesn't seem too important for now.
